### ISSUE TITLE
Google Button is not styling

### ISSUE THREAD

**Issue by falwickster** [tanis2000/meteor-bootstrap-social#1]
Class btn-google is not working, but when I add bootstrap-social.css to the project, it's styling correctly.
With this package (without css stylesheet) I tested btn-bitbucket and btn-facebook and it's working

**Comment by tanis2000** [comment]
It might be a problem with the version i packaged. I'll try updating to the latest as soon as I'm back in the office

**Comment by falwickster** [comment]
Hi! It might be obvious...the reason "btn-google" is not working because Your stylesheet points to the class "btn-google-plus". lipis/bootstrap stylesheet which I used, points to "btn-google"

**Comment by tanis2000** [comment]
I've just updated the included version of the CSS to the latest. Please let me know if it fixes this issue.

**Comment by falwickster** [comment]
Thanks Valerio. Problem solved
